---
abstract: 'DBIC for SQLHackers Table of Contents'
author:
  - 'Jess Robinson <castaway@desert-island.me.uk>, L<http://metacpan.org/author/JROBINSON>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: DBIx::Class::Manual::SQLHackers
name: DBIx-Class-Manual-SQLHackers
no_index:
  directory:
    - inc
resources:
  IRC: irc://irc.perl.org/#dbix-class
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DBIx-Class-Manual-SQLHackers
  homepage: http://dbix-class.org/manual/
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/dbsrgits/DBIx-Class-Manual-SQLHackers.git
version: 1.1
